version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./config/frontend/Dockerfile
      target: frontend-base
    stdin_open: true
    image: react-frontend:latest
    container_name: frontend
    hostname: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - nodemodules-frontend:/app/node_modules:z
      - ./frontend:/app:z
    
volumes:
  nodemodules-frontend: {}